#!/bin/sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
# umask 022




# ===APP CONFIGURATION===
# ---Shell Identifiers---
# See launch shell in launch script
export FISH_ID=xPV2iC
export IPYTHON_ID=wS77gy
export ZSH_ID=NdoBv7
# ------

# ---Default Apps---
export EDITOR=emacs
# ======



# ===DIRECTORY VARIABLES===

# ---Project Directories---
export BIN=~/Gray/AUTOMATE # Personal scripts project
export ARCHIVES=Gray/FILER/Archives # Project Archives
# ------

# ---Filesystem Mounts---
export DRIVE=~/Projects/FILER/Drive # Google Drive mount
export WIN=~/Projects/FILER/Windows # Noseer mount
export PHONE=~/Projects/FILER/Phone # MiniSeer  mount
export LINX=~/Projects/FILER/Linux # AllSeer mount
# ------

# ---Useful Directories---
export FRC="$DRIVE/Code-Orange (TECH)/BUILD/EverGreen #7112/FRC 2020-21/צוותים/תוכנה/" # Software Crew drive folder
export WALLPAPERS="$MEDIA/Photos/Wallpapers" # Wallpaper directory
export TEMPLATE=~/.lyx/templates # LyX Templates
# ------

# ---Installation Homes---
export EMACS_HOME=~/.emacs.d # Emacs Installation Home
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ # Java installation home
export GOROOT=/usr/local/go # go Installation Home
export GOPATH=~/.go # Go packages dir
# ------
# ======

# ===PATH ADDITIONS===
export PATH=$(echo $BIN/* | sed 's/ /:/g'):$PATH # Personal scripts (all directories under AUTOMATE, colon delimited)
export PATH=$PATH:~/.local/bin # Local bin
export PATH=$PATH:$EMACS_HOME/bin # emacs bin
export PATH=$PATH:$JAVA_HOME/bin # java bin
export PATH=$PATH:$GOROOT/bin # go bin
export PATH=$PATH:$GOPATH # go packages
export PATH=$PATH:$GOPATH/bin # go packages
# ======


# ===ALIASES & REMAPPINGS===

# ---Aliases---
alias del="rmtrash"
alias edit="emacs"
alias mv='mv -i'
alias cp='cp -i'
alias xcopy="xclip -sel clip"
alias xpaste="xclip -sel clip -o"
alias suspend='"$BIN/Launch/suspend"'
alias hibernate='"$BIN/Launch/hibernate"'
alias cat='batcat --paging=never'
# ------

# ---Remapping Functions---
exa() {
    _exa -I "*.lyx~:*.lyx#:__pycache__"$@
}


ls() {
    _ls -I "{*.lyx~,*.lyx#,__pycache__}"
}

emacs() { # If emacs is running, open a new frame; otherwise start it
    if test -e "/tmp/emacs1000/server"; then
        emacsclient -t -a emacs -nc $1
    else
        emacs $@
    fi
}
# ------
# ======

# === SDK-Man Configuration ===
export SDKMAN_DIR="$HOME/.sdkman"
[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ] && . "$HOME/.sdkman/bin/sdkman-init.sh"
# ======
