#!/bin/sh

[ -f ~/Gray/CONFIG/Configs/sh/sh/confdirs.sh ] && . ~/Gray/CONFIG/Configs/sh/sh/confdirs.sh

[ -f "$SH_DIR/local.sh" ] && . "$SH_DIR/local.sh"
[ -f "$SH_DIR/search-engines.sh" ] && . "$SH_DIR/search-engines.sh"
[ -f  "$SH_DIR/app_aliases.sh" ] && . "$SH_DIR/app_aliases.sh"

# ===APP CONFIGURATION===
# ---Shell Identifiers---
# See launch shell in launch script
export FISH_ID=xPV2iC
export IPYTHON_ID=wS77gy
export ZSH_ID=NdoBv7

# ---
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
# ------

# ---Default Apps---
export EDITOR=emacs
# ======



# ===DIRECTORY VARIABLES===

# ---Project Directories---
export BIN=~/Gray/AUTOMATE # Personal scripts project
export CONFIG=~/Gray/CONFIG
export FILER=~/Gray/CONFIG

export TMP=~/Gray/FILER/tmp
export BOIDEM=~/Gray/FILER/Boidem
export ARCHIVES=Gray/FILER/Archives # Project Archives
# ------

# ---Filesystem Mounts---
export DRIVE=~/Projects/FILER/Drive # Google Drive mount
export WIN=~/Projects/FILER/Windows # Noseer mount
export PHONE=~/Projects/FILER/Phone # MiniSeer  mount
export LINX=~/Projects/FILER/Linux # AllSeer mount
# ------

# ---Useful Directories---
export FRC="$DRIVE/Code-Orange (TECH)/BUILD/EverGreen #7112/FRC 2020-21/צוותים/תוכנה/" # Software Crew drive folder
export WALLPAPERS="$MEDIA/Photos/Wallpapers" # Wallpaper directory
export TEMPLATE=~/.lyx/templates # LyX Templates
# ------

# ---Installation Homes---
export EMACS_HOME=~/.emacs.d # Emacs Installation Home
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ # Java installation home
export GOROOT=/usr/local/go # go Installation Home
export GOPATH=~/.go # Go packages dir
# ------
# ======

# ===PATH ADDITIONS===
export PATH=$(echo $BIN/* | sed 's/ /:/g'):$PATH # Personal scripts (all directories under AUTOMATE, colon delimited)
export PATH=$PATH:~/.local/bin # Local bin
export PATH=$PATH:$EMACS_HOME/bin # emacs bin
export PATH=$PATH:$JAVA_HOME/bin # java bin
export PATH=$PATH:$GOROOT/bin # go bin
export PATH=$PATH:$GOPATH # go packages
export PATH=$PATH:$GOPATH/bin # go packages
# ======


# ===ALIASES & REMAPPINGS===

# ---Aliases---
alias del="rmtrash"
alias edit="emacs"
alias mv='mv -i'
alias cp='cp -i'
alias suspend='"$BIN/Launch/suspend"'
alias hibernate='"$BIN/Launch/hibernate"'
alias cat='bat --paging=never'
# ------

# ---Remapping Functions---
exa() {
    _exa -I "*.lyx~|*.lyx#|__pycache__" $@
}



if alias ls > /dev/null 2>&1; then # ls is commonly aliased by default configuration files which may not have neem overriden.
    unalias ls
fi

ls() {
    _ls -I "{*.lyx~,*.lyx#,__pycache__}" $@
}

emacs() { # If emacs is running, open a new frame; otherwise start it
    if test -e "/tmp/emacs1000/server"; then
        emacsclient -t -a emacs -nc $@
    else
        $PREFIX/bin/emacs $@
    fi
}
# ------
# ======

# === SDK-Man Configuration ===
export SDKMAN_DIR="$HOME/.sdkman"
[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ] && . "$HOME/.sdkman/bin/sdkman-init.sh"
# ======
