# Shell variables
# Generated by 'wal'
wallpaper='/data/data/com.termux/files/home/storage/dcim/Camera/20210721_120404.jpg'

# Special
background='#0f1010'
foreground='#dddedf'
cursor='#dddedf'

# Colors
color0='#0f1010'
color1='#8C847B'
color2='#6B798D'
color3='#748AA7'
color4='#91969E'
color5='#B0AFB2'
color6='#BDBEC2'
color7='#dddedf'
color8='#9a9b9c'
color9='#8C847B'
color10='#6B798D'
color11='#748AA7'
color12='#91969E'
color13='#B0AFB2'
color14='#BDBEC2'
color15='#dddedf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
